# Generated by Django 5.1.5 on 2025-01-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('loan_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('dependents', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=20)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('applicant_income', models.FloatField()),
                ('coapplicant_income', models.FloatField()),
                ('loan_amount', models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100), (120, 120), (150, 150), (180, 180), (200, 200), (250, 250), (300, 300), (350, 350), (400, 400), (450, 450), (500, 500)])),
                ('loan_amount_term', models.IntegerField(choices=[(12, 12), (24, 24), (36, 36), (48, 48), (60, 60), (84, 84), (120, 120), (160, 160), (180, 180), (240, 240), (360, 360)])),
                ('credit_history', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('property_area', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('Semiurban', 'Semiurban')], max_length=20)),
                ('loan_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'estimator_loan_application',
            },
        ),
    ]
